name: ReadMe
version: ${pluginVersion}
main: cc.dsnb.readme.ReadME
api-version: 1.13
author: DongShaoNB
website: https://dsnb.cc
description: Show ReadMe after player joins server
softdepend:
  - AuthMe
  - PlaceholderAPI

commands:
  readme:
    description: ReadME main command
    permission: readme.admin

permissions:
  readme.admin:
    default: op